# Generated by Django 5.1.7 on 2025-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0002_legend_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='description',
            field=models.CharField(default='No description yet', max_length=250),
        ),
    ]
